# Generated by Django 5.0.2 on 2024-11-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability_name', models.CharField(max_length=255)),
                ('ability_url', models.CharField(max_length=255)),
                ('hidden', models.BooleanField(default=False)),
                ('slot', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('cries', models.CharField(max_length=255)),
                ('height', models.CharField(max_length=255)),
                ('weight', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
            ],
        ),
    ]
